model:
  name: bond_predictor
  node_dim: 256
  edge_dim: 64
  node_indicator: True
  center_pos_mode: protein
  knn: 32
  cutoff_mode: knn
  encoder:
    backbone: EGNN
    num_blocks: 9
    cutoff: 20
    use_gate: True
    update_edge: True
    update_pos: False  # pos should not be updated
  diff:
    num_timesteps: 1000
    time_dim: 10
    categorical_space: discrete
    diff_pos:
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3
    diff_atom: 
      init_prob: tomask
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3

train:
  seed: 2023
  batch_size: 4
  num_workers: 4
  pin_memory: True
  max_iters: 600000
  val_freq: 4000
  train_report_iter: 100
  pos_noise_std: 0.05
  max_grad_norm: 50.0
  use_amp: True
  resume: False
  resume_ckpt: None
  prev_model: False
  prev_ckpt: None
  optimizer:
    type: adamw
    lr: 1.e-4
    weight_decay: 1.e-4
    beta1: 0.99
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 10
    min_lr: 1.e-8

data:
  name: protein_ligand
  path: data/PDBbind_v2020_pocket10
  split: data/PDBbind_pocket10_split.pt
  #path: data/crossdocked_v1.1_rmsd1.0_pocket10
  #split: data/crossdocked_pocket10_pose_split.pt
  transform:
    ligand_atom_mode: aromatic # [basic, aromatic, full]
    random_rot: False
    sample: False
